### ISSUE TITLE
Performance dropping with --blur_loss

### ISSUE THREAD

**Issue by yjh9001** [cszhilu1998/SelfIR#1]
I compared the results when "--blur_loss" value set to 0 and 2. However, when the --blur_loss value was set to 2, the PSNR result was about 0.2 lower.(performance dropped when --blur_loss 2) I left the other hyperparameters unchanged, but do I need to modify any of them?
* I used the GOPRO_Large dataset and kept the other settings the same.

**Comment by cszhilu1998** [comment]
I recommend first pre-training the model with --blur_loss 0 and then fine-tuning it with --blur_loss 2.
